### ISSUE TITLE
Some bugs(?) with get image from UIImageView

### ISSUE THREAD

**Issue by xspyhack** [ibireme/YYWebImage#41]
There is a bug when I get image from a UIImageView looks like
`UIImage *shareImage = self.imageView.image;`
And then,  use UIActivityViewController to share to Social Network(e.g. Twitter, Weibo), it will case a problem - can not post, because UIAcvitityItem can't get the image.

But SDWebImage is working well.

Actually, I can use `UIImage *shareImage = [UIImage imageWithCGImage:self.imageView.image]` to fix this bug(?).

There is my test demo.
[Test Code](https://github.com/xspyhack/YYWebImageDemo)

**Comment by ibireme** [comment]
It returns `YYImage` instead of `UIImage` to support animated APNG/WebP/GIF, and `YYImage` is subclass of `UIImage`. 

I don't know why `UIActivityViewController` doesn't support UIImage subclass, but you can try these workaround:

1. Add `YYWebImageOptionIgnoreAnimatedImage` flag to ignore animated image.
2. Use `NSData` instead of `UIImage`, for example: [YYPhotoGroupView.m#L751-L765](https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/YYPhotoGroupView.m#L751-L765)
3. Convert `YYImage` to `UIImage` (your demo code).

**Comment by xspyhack** [comment]
Thank you. (happy new year :D
